## Below CRD First allows access
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: fakeapp-static-auth
  namespace: fakeapp
spec:
  # vaultConnectionRef: default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: default-kv-v2-access
    serviceAccount: default
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: fakeapp
  name: fakeapp-credentials
spec:
  vaultAuthRef: fakeapp-static-auth
  mount: kv-v2
  type: kv-v2
  path: fakeapp/credentials
  refreshAfter: 10s
  ## Create a k8s secret named akeapp-credentials if it doesnt exisits
  destination:
    create: true
    name: fakeapp-credentials
  # Below tells k8s which resources need to be restarted whenever the Secret updated/changed
  rolloutRestartTargets:
  - kind: Deployment
    name: fakeapp